/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MembershipRouteRouteImport } from './routes/membership/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as MembershipIndexRouteImport } from './routes/membership/index'
import { Route as PortalResetPasswordRouteImport } from './routes/portal/reset-password'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalForgotPasswordRouteImport } from './routes/portal/forgot-password'
import { Route as MembershipConfirmationRouteImport } from './routes/membership/confirmation'

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRouteRoute = MembershipRouteRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipIndexRoute = MembershipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembershipRouteRoute,
} as any)
const PortalResetPasswordRoute = PortalResetPasswordRouteImport.update({
  id: '/portal/reset-password',
  path: '/portal/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalForgotPasswordRoute = PortalForgotPasswordRouteImport.update({
  id: '/portal/forgot-password',
  path: '/portal/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipConfirmationRoute = MembershipConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => MembershipRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/membership': typeof MembershipRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/membership/confirmation': typeof MembershipConfirmationRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/membership/': typeof MembershipIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/membership/confirmation': typeof MembershipConfirmationRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/membership': typeof MembershipIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/membership': typeof MembershipRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/membership/confirmation': typeof MembershipConfirmationRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/membership/': typeof MembershipIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/membership'
    | '/about'
    | '/donate'
    | '/events'
    | '/membership/confirmation'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/reset-password'
    | '/membership/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate'
    | '/events'
    | '/membership/confirmation'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/reset-password'
    | '/membership'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/membership'
    | '/about'
    | '/donate'
    | '/events'
    | '/membership/confirmation'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/reset-password'
    | '/membership/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MembershipRouteRoute: typeof MembershipRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  PortalForgotPasswordRoute: typeof PortalForgotPasswordRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalResetPasswordRoute: typeof PortalResetPasswordRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/': {
      id: '/membership/'
      path: '/'
      fullPath: '/membership/'
      preLoaderRoute: typeof MembershipIndexRouteImport
      parentRoute: typeof MembershipRouteRoute
    }
    '/portal/reset-password': {
      id: '/portal/reset-password'
      path: '/portal/reset-password'
      fullPath: '/portal/reset-password'
      preLoaderRoute: typeof PortalResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/forgot-password': {
      id: '/portal/forgot-password'
      path: '/portal/forgot-password'
      fullPath: '/portal/forgot-password'
      preLoaderRoute: typeof PortalForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/confirmation': {
      id: '/membership/confirmation'
      path: '/confirmation'
      fullPath: '/membership/confirmation'
      preLoaderRoute: typeof MembershipConfirmationRouteImport
      parentRoute: typeof MembershipRouteRoute
    }
  }
}

interface MembershipRouteRouteChildren {
  MembershipConfirmationRoute: typeof MembershipConfirmationRoute
  MembershipIndexRoute: typeof MembershipIndexRoute
}

const MembershipRouteRouteChildren: MembershipRouteRouteChildren = {
  MembershipConfirmationRoute: MembershipConfirmationRoute,
  MembershipIndexRoute: MembershipIndexRoute,
}

const MembershipRouteRouteWithChildren = MembershipRouteRoute._addFileChildren(
  MembershipRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MembershipRouteRoute: MembershipRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  PortalForgotPasswordRoute: PortalForgotPasswordRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalResetPasswordRoute: PortalResetPasswordRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
